name = "stardew-presence"
main = "worker.js"
compatibility_date = "2024-01-01"

# Serve static web dashboard directly from web/
[assets]
directory = "./web"
binding = "ASSETS"

# R2 bucket binding for storing dynamic character avatars
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "stardew-presence"
